### ISSUE TITLE
About the LPIPS

### ISSUE THREAD

**Issue by happyday521** [Zhangjinso/PISE#4]
Hi， great work！
I have a problem about the results of LPIPS. Since you split the dataset with the same way as GFLA , why are the LPIPS results in your paper(GFLA: 0.2219, PATN:0.2520) different from that reported in the paper of GFLA?(GFLA: 0.2341, PATN:0.2533). What is your test setup？
Thanks！

**Comment by Zhangjinso** [comment]
Hi, we compute lpips using https://github.com/richzhang/PerceptualSimilarity, and the inputs are cropped to 256X176 due to the valid background.
For the results of GFLA, most methods as well as ours use input images of size 256X176 and padding to 256X256. The input in the paper of GFLA is from high-resolution images  and resized them directly to 256X256, which contain more information compared with low-resolution images. In our paper, we take 256X256 images resized from 256X176 as input of GFLA, which can be the main reason.

**Comment by happyday521** [comment]
Got it. Thanks for your reply.
